
package csg;

/**
 * This enum provides a list of all the user interface
 * text that needs to be loaded from the XML properties
 * file. By simply changing the XML file we could initialize
 * this application such that all UI controls are provided
 * in another language.
 * 
 * @author Itai Flam
 * @version 1.0
 */
public enum CourseSiteGeneratorProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    DEFAULT_PICTURES_ICON,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    SUBMIT_HOURS_TEXT,
    SEMESTER_TEXT,
    SUBJECT_TEXT,
    NUMBER_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    INSTRUCTOR_NAME_TEXT,
    INSTRUCTOR_HOME_TEXT,
    EXPORT_DIRECTORY_TEXT,
    EXPORT_DIRECTORY_DEFAULT_TEXT,
    CHANGE_TEXT,
    SUMMER_TEXT,
    FALL_TEXT,
    WINTER_TEXT,
    SPRING_TEXT,
    COURSE_DETAILS_TEXT,
    COURSE_INFO_TEXT,
    TITLE_DEFAULT_TEXT,
    INSTRUCTOR_NAME_DEFAULT_TEXT,
    INSTRUCTOR_HOME_DEFAULT_TEXT,
    SITE_TEMPLATE_TEXT,
    SELECTED_TEMPLATE_TEXT,
    TEMPLATE_DEFAULT_TEXT,
    SELECT_TEMPLATE_TEXT,
    SITE_PAGES_TEXT,
    USE_TEXT,
    NAVBAR_TITLE_TEXT,
    FILE_NAME_TEXT,
    SCRIPT_TEXT,
    PAGE_STYLE_TEXT,
    BANNER_IMG_TEXT,
    LEFT_IMG_TEXT,
    RIGHT_IMG_TEXT,
    STYLESHEET_TEXT,
    STYLESHEET_MESSAGE,
    
    
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE APP
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    INCORRECT_FORMAT_TA_EMAIL_TITLE,
    INCORRECT_FORMAT_TA_EMAIL_MESSAGE,
    WRONG_HOURS_FORMAT_TITLE,
    WRONG_HOURS_FORMAT_MESSAGE,
    CHANGE_HOURS_PROMPT_TITLE,
    CHANGE_HOURS_PROMPT_MESSAGE
    
}
